### ISSUE TITLE
How to replace in an object key

### ISSUE THREAD

**Issue by iPherian** [JakubMifek/SelectTransform#9]
Great project!

I got error 'Wrong format of input template- {{fruitName}} (No executor found)'.

Probably just don't know how to use this library 😄

<details>
<summary>stacktrace</summary>
Error: Wrong format of input template- {{fruitName}} (No executor found)
    at new StError ([project_dir]\node_modules\selecttransform\dist\common.js:24:23)
    at Object.<anonymous> ([project_dir]\node_modules\selecttransform\dist\common.js:29:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> ([project_dir]\node_modules\selecttransform\dist\internal.js:12:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
</details>

When doing:

```javascript
const ST = require('selecttransform').SelectTransform;

const st = new ST();

let data = {'fruitName': 'fruit'};

let template = {'{{fruitName}}': 'apple'};

let transformed = st.transformSync(template, data);
```

**Comment by JakubMifek** [comment]
Hi @iPherian, I am glad you enjoy the project.

I don't believe the library is able to transform keys of objects but values only. Keys are usually used for functions. However, I can see how that could be useful..

Unfortunately, my hands are full recently. If you feel like contributing, you could inspect the code and try to come up with a solution - I believe this would be `transform.ts` file. If not, I will try to look into it in a few days.

Thanks.

**Comment by iPherian** [comment]
@JakubMifek thanks, i'll give it a go
